// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdCwLc0BqL2vJoUmk3WBTCZft2QarfXaI',
    appId: '1:63526754925:web:d02616a163919bda04fd64',
    messagingSenderId: '63526754925',
    projectId: 'flutter-ecommerce-155e5',
    authDomain: 'flutter-ecommerce-155e5.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-155e5.appspot.com',
    measurementId: 'G-Y3M7LX6M8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVTP3KjFb4cX89cd3GeleEj4f7I0u4Mik',
    appId: '1:63526754925:android:585bc99fcff6b1ae04fd64',
    messagingSenderId: '63526754925',
    projectId: 'flutter-ecommerce-155e5',
    storageBucket: 'flutter-ecommerce-155e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZBJNQNvlvd1gDOIyadB7tcYYhW3e5fc4',
    appId: '1:63526754925:ios:42ca82f452df320304fd64',
    messagingSenderId: '63526754925',
    projectId: 'flutter-ecommerce-155e5',
    storageBucket: 'flutter-ecommerce-155e5.appspot.com',
    iosBundleId: 'com.example.flutterEcommerce155e5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZBJNQNvlvd1gDOIyadB7tcYYhW3e5fc4',
    appId: '1:63526754925:ios:42ca82f452df320304fd64',
    messagingSenderId: '63526754925',
    projectId: 'flutter-ecommerce-155e5',
    storageBucket: 'flutter-ecommerce-155e5.appspot.com',
    iosBundleId: 'com.example.flutterEcommerce155e5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdCwLc0BqL2vJoUmk3WBTCZft2QarfXaI',
    appId: '1:63526754925:web:0575f73b7d0c1c0c04fd64',
    messagingSenderId: '63526754925',
    projectId: 'flutter-ecommerce-155e5',
    authDomain: 'flutter-ecommerce-155e5.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-155e5.appspot.com',
    measurementId: 'G-J20WESB25K',
  );
}
